### ISSUE TITLE
Release v12.0.0

### ISSUE THREAD

**Issue by subhod-i** [aeternity/aepp-sdk-js#1535]
- [x] typescript for everything #1215
- [x] **auto-generate and publish API reference documentation.** implemented in 6d5b7bdc6680a3bedaebce7b689b5566ad6536d3
- [x] support IDE features: Code completion, Goto definition, Documentation (isn't it the same as the first or do we need something special here?)
- [x] already opened pull requests related to ts
- [x] #1536 
- [x] #1537 (rejected, too difficult)
- [x] #1551 
- [x] #1546 
- [x] #1520 
- [x] examples and guides working.
- [x] ensure that aepp-wallet connection works between sdk@11 and sdk@12.
- [x] #1561
- [x] #1559 
- [x] #1565 
- [x] #1567 
- [x] #1563 
- [x] #1549 (rejected, needs to rebase)

**Comment by subhod-i** [comment]
| SDK \ Wallet | v11 | v12   |
|--------------|-----|-------|
| v11          | ✅   | #1559 |
| v12          |     |       |
