### ISSUE TITLE
explicit usage of `bytecode`, `ACI` and `contract address` / get rid of http compiler dependency

### ISSUE THREAD

**Issue by marc0olo** [aeternity/aepp-sdk-js#1681]
as discussed in the workshops pre-conference we want to enforce separate compilation in a prior step by allowing the developers to get the contract instance only by:
- bytecode / aci (for deployment and further interaction)
- aci / contract address (for existing contracts)

## TODOs
- [ ] the SDK should NOT allow implicit contract compilation
   - it must NOT be possible to initialize a contract instance by providing source code anymore
- [ ] the SDK must accept the ACI in the format returned by the http compiler and we can omit the `interface` attribute there (related to https://github.com/aeternity/aepp-contracts/issues/78)
- [ ] the SDK must return the ACI in the format returned by the http compiler

## Further TODOs (follow up discussion 10.11.2022)
We even want to get rid of http compiler depencency. The http compiler is only needed in applications like "custom token creator" or web IDEs like AEstudio and can be bundled along with those applications. The few lines of code to compile and get bytecode/ACI from http compiler can be implemented on application level. 99,99% of aepps do NOT need the http compiler at all.

- [ ] get rid of ALL functionality that interacts with **http** compiler
  - requires adjustments in integration tests, we need to replace http compiler with local (pre-installed) CLI compiler

# Documentation
- [ ] adjust the documentation accordingly

**Comment by davidyuk** [comment]
would be an option to accept ACIs in both original and camelCased formats everywhere and to return camelCased?

**Comment by marc0olo** [comment]
> would be an option to accept ACIs in both original and camelCased formats everywhere and to return camelCased?

my personal opinion is that we should be consistent. so if we really want camelCase for the ACI we should adapt the format which the compiler returns.

other opinions? @thepiwo @kenodressel @nikita-fuchs @loxs @dincho @hanssv

**Comment by hanssv** [comment]
I don't have an opinion, feel free to decide on something and if necessary change the HTTP compiler

**Comment by kenodressel** [comment]
@davidyuk why do we need a camelCase notation for the ACI?

**Comment by Kalovelo** [comment]
Even if camelCase is the JS convention I would vote for the one which requires less maintainability, and I believe keeping the original requires less (also more consistent)

**Comment by nikita-fuchs** [comment]
I've kept it camel case in the devmode API as it seems to be the standard way for Erlang things, it's actually a good way of marking data coming from Erlang components. Me or @thepiwo could adapt in aesophia_http to not bother @hanssv with this, but if there is no explicit technical need besides conventions, i would propose to leave things as they are. But I have no strong opinion on here.

**Comment by marc0olo** [comment]
so, what's the decision now? :-)

based on the recent discussion I would say we stick to the original json returned by http compiler

**Comment by loxs** [comment]
Sounds like the saner decision

**Comment by davidyuk** [comment]
> why do we need a camelCase notation for the ACI?

it is the outcome of autorest, it converting the case of fields in the swagger file to make it named friendly to js

**Comment by davidyuk** [comment]
The proposed change regarding ACI is a workaround. I would prefer to have ACI type generated by autorest from swagger file than doing myself. The same problem may happen with other tools to generate api by swagger file, also autorest can generate for C#, PowerShell, Go, Java, Python.

Can we have a new version of ACI format instead? To drop `interface` field (as we don't need it in most cases), and make all fields a single word, then we won't have this compatibility issue.
```
aci.encoded_aci.contract => aci.contract
aci.encoded_aci.namespace => aci.namespace
aci.external_encoded_aci => aci.external ?
aci.*.type_defs => aci.*.types 🤷‍♀️
```

This would require more work but maybe it would work better in the long term.

**Comment by loxs** [comment]
Erlang and its (lack of) tooling is not the best place to play games with such re-factorings. I would consider it last resort. Only change it if everything else is not possible.

**Comment by davidyuk** [comment]
> I am wondering if there is just a possibility to avoid auto-conversion from autorest when calling the http compiler to receive the ACI.

I can remove the corresponding part of the swagger file on the step of api generation. And then create a wrapper around generated api that would have a manually specified type. This is quite hacky, and we may have to do the same in different environments.

> Erlang and its (lack of) tooling is not the best place to play games with such re-factorings.

ACI is just interface, not internals, I was doing something like this before on the compiler side 🤷‍♀️. I think if we found a lack like this at any level it should be fixable, not necessary to do it immediately, but be able to plan to do it at some point. Otherwise, we would be too nervous when creating new apis or would live with poor apis.

It is not a big effort to implement my proposal:
1. to make a new compiler release with a separate endpoint returning new ACI (with no breaking changes)
2. support analog of `type_def` in a single place in calldata library (not a breaking change)
3. switch to a new ACI in SDK

And everything would be working smoothly. In the next breaking release of compiler, the old aci can be removed.

Switching back from `encodedAci` to `encoded_aci` would make the same about of breaking changes in sdk compared to my proposal.

Also, would be nice to add openapi@3 in compiler to describe aci structure better, also we had problems describing the error structure before.

Is compilation takes much more time than generating aci? Maybe we can have a single endpoint returning both of them to avoid an extra request. And at the same time, we can introduce the aci format I proposed.

**Comment by marc0olo** [comment]
## Changes in Contract API

> * it doesn't ensure the performance benefits (the developer can do exactly the same just explicitly)

yes, but it would make very clear that it's not required and we all agreed that this is the better approach.

> * the intended optimization is already possible (maybe instead of disallowing initialization with source code we can improve documentation, add a warning about doing implicit compilation)

we just do not want to allow the implicit compilation anymore by default

> * breaks OOP logic a bit, I would expect that Contract instance can be created by source code

I understand and we had that kind of discussion also at the workshop. we just want to educate people not "misusing" this. but it encourages more the "quick and dirty" path instead of the "correct path". compilation and bytecode generation is only needed once in real-world applications.

the only area where I think it's useful is during smart contract development where you effectively save 1 line of code by doing it implicitely. again, here we would have an additional line of code where we can tell people that bytecode is only needed once and ACI in combination with contract id can be used to interact with contract later on.

------------------------------------------

regarding your proposal -> I think we need to distinguish between:
- prod applications (frontend + backend)
- usage during development

you proposal absolutely makes sense during development. maybe this is a functionality we could think about in AEproject (cc @thepiwo)

## ACI format
I see you have a strong opinion on that one @davidyuk. I think if we do not break API and introduce a new endpoint in Sophia HTTP compiler I wouldn't have a problem with this. Could you propose all the changes in those repos then where needed and also update the docs accordingly that people know there is a new format of ACI in http compiler that is used in SDK? I just think we should proceed in some way here. Which way I don't really care. But I think it's discussed enough now 😅

**Comment by thepiwo** [comment]
I think for development its also ok to first have `generateAci` then a second step `getContractInstance`

**Comment by thepiwo** [comment]
I can do this with the current sdk as well, e.g. as done in https://contracts.aepps.com/

1. `const aci = await sdk.compilerApi.generateACI({ code, options: {} })`
2. `const contract = await sdk.getContractInstance({ aci, contractAddress })`

**Comment by thepiwo** [comment]
And to keep it simple we could maybe support both camelCase and underscore_case, but returning the original aci as returned from the compiler from `generateACI`

**Comment by thepiwo** [comment]
@loxs I would avoid touching aesophia or aesophia_http

**Comment by davidyuk** [comment]
> we just do not want to allow the implicit compilation anymore by default

It doesn't seem to be so bad from my perspective

> "quick and dirty" path

Actually, we can speed up interactions with compiler by enabling HTTP caching on the client side (so the compiler won't be requested if it was requested by this client before with the same arguments). And to speedup compiler response we can use a reverse http proxy to cache its responses. So, instead of forcing a developer to have his own cache we can ensure that SDK and compiler provide their own caching. It is not the best way to go, but would be good to improve caching, this would speedup the apps that use "quick and dirty" path.

> you proposal absolutely makes sense during development

I think this would work the same efficient in production

> Could you propose all the changes in those repos

I will do that 👌 sorry for being slow

**Comment by marc0olo** [comment]
so regarding ACI camelCase topic it's debatable from my perspective although majority thinks we should not touch the Erlang repos and introduces changes.

for the implicit initialization with source code please let's go the route we discussed in the castle. we should just not encourage this anymore. if somebody really want's to compile and initialize with source code only this can be provided in a helper function or however. the key point is we do not recommend this anymore. actually we want people to avoid doing that 😬

**Comment by dincho** [comment]
I see the discussion goes around only the HTTP compiler, but the norm should be CLI compiler, that is CLI compiler and HTTP compiler should probably generate the same ACI interface.

**Comment by marc0olo** [comment]
well initially it was about using the ACI as is. if @davidyuk stands on his point and wants to provide consistency and camelCase approach it should of course be applied to http compiler and cli compiler 😅 

I just wanna see this being done as soon as possible in whatever way 😭

**Comment by thepiwo** [comment]
I agree with @dincho but I would also be strongly for not changing the erlang code and returned format, also to provide some level of backwards compatibility with this approach.

**Comment by marc0olo** [comment]
> it is the outcome of autorest, it converting the case of fields in the swagger file to make it named friendly to js

this is a new discussion point btw @davidyuk. if possible we should avoid having autorest as regular dependency. ideally it's only a dev dependency in the future. is there anything that speaks against that route?

**Comment by marc0olo** [comment]
I saw @davidyuk creating multiple (some already approved and merged) pull requests in aesopha repositories. I provided my two cents to this topic.

also, we added another new task to get rid of http compiler here.

would love to get another comment of @davidyuk in regards to all of this. and then we have to execute, otherwise this will be a never ending story like wallet connection one-liner.

@nikita-fuchs I agree with the importance of wallet connection. but this here is currently more urgent. also we need to consider the best possible approach for wallet connection and not "just do sth." - we also discussed that pre-conference and unfortunately didn't find the time to pick this topic up 😞

**Comment by davidyuk** [comment]
So, the update from my side:

I figured out that ACI in http compiler and cli compiler are not the same, ACI in http have `externalAci`, `externalEncodedAci` fields and cli version just returns an array (calldata also uses this format), so at least they are not consistent and we have to fix it on erlang side. I've sent a PR to http compiler to add ACI in cli format to the output of `/compile` endpoint. Also, I've sent a PR to replace `type_defs` with `typedefs` in the compiler repo and it got merged. I propose to merge my changes and it would be needed to release:
- aesophia with a breaking change
- aesophia-http with a minor update
- calldata with a minor update
- sdk that uses new aci

I have prepared a tool to build contracts using webpack or a cli: https://github.com/aeternity/contract-builder
Please check it, this should be an easiest way to integrate smart contracts to any js app in the right way.

I don't think that we need to drop http compiler entirely because it already works somehow, it provides functionality like validate-byte-code, decode-calldata that are not easily available. I would implement several compiler classes (based on cli, http, and erlps-aesophia) instead and don't make http compiler preferred. So, sdk won't accept `compilerUrl` and won't have `setCompilerUrl` method, asking user to specify `onCompiler` option explicitly if needed to iterate with a compiler. We can leave the contract API as it is and the user will have to choose a compiler or use the `contract-builder` I proposed above, ideally, we need a guide to help the user to make a decision. The harm of implicit contract compilation doesn't seem obvious if used aesophia-cli or erlps-aesophia.

**Comment by marc0olo** [comment]
I fully support to finally achieve 100% consistency, no matter how we face this. regarding the approach I do not have a strong opinion and expect others to raise their voice (again) 😅 

on the http-compiler topic:
- the hosted http compiler will be shut down and we agreed on that
- any usage of http compiler would have to be hosted / spawned explicitly by the app/user that requires it. please consider this in your decision / approach @davidyuk

**Comment by dincho** [comment]
I'm just passing by to confirm what @marc0olo wrote above: the HTTP compiler will be shut down regardless of the decision in this issue and the JS SDK.

I'm not sure I understand the purpose of `validate-byte-code` what's the usecase ?

What data cannot be decoded with the calldata lib? I'm pretty sure we can add that to it? Example/usecase?

**Comment by marc0olo** [comment]
to be honest I don't care anymore. do what you want guys

**Comment by marc0olo** [comment]
the day has come 🙌 

dependency to http compiler also removed or still supported? @davidyuk

**Comment by davidyuk** [comment]
http compiler is still supported, but not required
